// ДЛЯ USER
// авторизация
// отлов введенных данных
export const USER_AUTH_INPUT_EMAIL_CHANGED = "USER_AUTH_INPUT_EMAIL_CHANGED";
export const USER_AUTH_INPUT_PASSWORD_CHANGED = "USER_AUTH_INPUT_PASSWORD_CHANGED";
// попытка входа в аккаунт
export const USER_TRY_TO_LOG_IN = "USER_TRY_TO_LOG_IN";
export const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export const USER_LOG_IN_FAILED = "USER_LOG_IN_FAILED";
//валидация полей авторизации
export const AUTH_USER_EMAIL_VALID = "AUTH_USER_EMAIL_VALID";
export const AUTH_USER_EMAIL_INVALID = "AUTH_USER_EMAIL_INVALID";
export const AUTH_MAIN_INVALID_MESSAGE = "AUTH_MAIN_INVALID_MESSAGE";

// восстановление пароля
// пока не нашел решения как отправить письма на почту, но компонент на фронте сделал
export const USER_RECOVER_INPUT_EMAIL_CHANGED = "USER_RECOVER_INPUT_EMAIL_CHANGED";
export const USER_RECOVER_SUCCESS = "USER_RECOVER_SUCCESS";
export const USER_RECOVER_FAILED = "USER_RECOVER_FAILED";
//валидация полей восстановления пароля
export const RECOVER_USER_EMAIL_VALID = "RECOVER_USER_EMAIL_VALID";
export const RECOVER_USER_EMAIL_INVALID = "RECOVER_USER_EMAIL_INVALID";
export const RECOVER_MAIN_INVALID_MESSAGE = "RECOVER_MAIN_INVALID_MESSAGE";

// регистрация
// отлов изменений в input
export const USER_REG_INPUT_NAME_CHANGED = "USER_REG_INPUT_NAME_CHANGED";
export const USER_REG_INPUT_SURNAME_CHANGED = "USER_REG_INPUT_SURNAME_CHANGED";
export const USER_REG_INPUT_POSITION_CHANGED = "USER_REG_INPUT_POSITION_CHANGED";
export const USER_REG_INPUT_EMAIL_CHANGED = "USER_REG_INPUT_EMAIL_CHANGED";
export const USER_REG_INPUT_PASSWORD_CHANGED = "USER_REG_INPUT_PASSWORD_CHANGED";
export const USER_REG_INPUT_REPEAT_PASSWORD_CHANGED = "USER_REG_INPUT_REPEAT_PASSWORD_CHANGED";
export const USER_REG_INPUT_BIRTHDATE_CHANGED = "USER_REG_INPUT_BIRTHDATE_CHANGED";
// попытка зарегистрироваться
export const USER_TRY_TO_REGISTER = "USER_TRY_TO_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
// валидация полей регистрации
export const REG_USER_NAME_VALID = "REG_USER_NAME_VALID";
export const REG_USER_NAME_INVALID = "REG_USER_NAME_INVALID";
export const REG_USER_SURNAME_VALID = "REG_USER_SURNAME_VALID";
export const REG_USER_SURNAME_INVALID = "REG_USER_SURNAME_INVALID";
export const REG_USER_POSITION_INVALID = "REG_USER_POSITION_INVALID";
export const REG_USER_POSITION_VALID = "REG_USER_POSITION_VALID";
export const REG_USER_EMAIL_VALID = "REG_USER_EMAIL_VALID";
export const REG_USER_EMAIL_INVALID = "REG_USER_EMAIL_INVALID";
export const REG_USER_PASSWORD_VALID = "REG_USER_PASSWORD_VALID";
export const REG_USER_PASSWORD_INVALID = "REG_USER_PASSWORD_INVALID";
export const REG_USER_REPEAT_PASSWORD_VALID = "REG_USER_REPEAT_PASSWORD_VALID";
export const REG_USER_REPEAT_PASSWORD_INVALID = "REG_USER_REPEAT_PASSWORD_INVALID";
export const REG_USER_BIRTHDATE_VALID = "REG_USER_BIRTHDATE_VALID";
export const REG_USER_BIRTHDATE_INVALID = "REG_USER_BIRTHDATE_INVALID";
export const REG_EMPTY_FIELD_MESSAGE = "REG_EMPTY_FIELD_MESSAGE";
export const REG_MAIN_INVALID_MESSAGE = "REG_MAIN_INVALID_MESSAGE";

// загрузка всех пользователей (вкладка Colleagues)
export const GET_ALL_USERS_LOADING = "GET_ALL_USERS_LOADING";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";

// загрузка персональных данных
export const GET_PERSONAL_DATA_LOADING = "GET_PERSONAL_DATA_LOADING";
export const GET_PERSONAL_DATA_SUCCESS = "GET_PERSONAL_DATA_SUCCESS";
export const GET_PERSONAL_DATA_FAILED = "GET_PERSONAL_DATA_FAILED";
// удаление своего аккаунта
export const USER_TRY_TO_DELETE_ACCOUNT = "USER_TRY_TO_DELETE_ACCOUNT";
export const USER_DELETE_ACCOUNT_SUCCESS = "USER_DELETE_ACCOUNT_SUCCESS";
export const USER_DELETE_ACCOUNT_FAILED = "USER_DELETE_ACCOUNT_FAILED";
// получение и изменение персональных данных
export const USER_CHANGE_DATA_INPUT_NAME_CHANGED = "USER_CHANGE_DATA_INPUT_NAME_CHANGED";
export const USER_CHANGE_DATA_INPUT_SURNAME_CHANGED = "USER_CHANGE_DATA_INPUT_SURNAME_CHANGED";
export const USER_CHANGE_DATA_INPUT_PASSWORD_CHANGED = "USER_CHANGE_DATA_INPUT_PASSWORD_CHANGED";
export const USER_CHANGE_DATA_INPUT_BIRTHDATE_CHANGED = "USER_CHANGE_DATA_INPUT_BIRTHDATE_CHANGED";
export const USER_TRY_TO_CHANGE_PERSONAL_DATA = "USER_TRY_TO_CHANGE_PERSONAL_DATA";
export const USER_CHANGED_PERSONAL_DATA_SUCCESS = "USER_CHANGED_PERSONAL_DATA_SUCCESS";
export const USER_CHANGED_PERSONAL_DATA_FAILED = "USER_CHANGED_PERSONAL_DATA_FAILED";
// валидация полей изменения персональных данных
export const USER_CHANGE_PERS_DATA_NAME_VALID = "USER_CHANGE_PERS_DATA_NAME_VALID";
export const USER_CHANGE_PERS_DATA_NAME_INVALID = "USER_CHANGE_PERS_DATA_NAME_INVALID";
export const USER_CHANGE_PERS_DATA_SURNAME_VALID = "USER_CHANGE_PERS_DATA_SURNAME_VALID";
export const USER_CHANGE_PERS_DATA_SURNAME_INVALID = "USER_CHANGE_PERS_DATA_SURNAME_INVALID";
export const USER_CHANGE_PERS_DATA_PASSWORD_VALID = "USER_CHANGE_PERS_DATA_PASSWORD_VALID";
export const USER_CHANGE_PERS_DATA_PASSWORD_INVALID = "USER_CHANGE_PERS_DATA_PASSWORD_INVALID";
export const USER_CHANGE_PERS_DATA_BIRTHDATE_INVALID = "USER_CHANGE_PERS_DATA_BIRTHDATE_INVALID";
export const USER_CHANGE_PERS_DATA_BIRTHDATE_VALID = "USER_CHANGE_PERS_DATA_BIRTHDATE_VALID";
export const USER_CHANGE_EMPTY_FIELD_MESSAGE = "USER_CHANGE_EMPTY_FIELD_MESSAGE";
export const CHANGE_PERS_DATA_MAIN_INVALID_MESSAGE = "CHANGE_PERS_DATA_MAIN_INVALID_MESSAGE";
// выход из аккаунта
export const USER_LOG_OUT = "USER_LOG_OUT";



// ДЛЯ CLIENT
// автоматическая загрузка Клиентов из базы
export const GET_CLIENT_LOADING = "GET_CLIENT_LOADING";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILED = "GET_CLIENT_FAILED";
// создание нового поля для Клиента
export const CREATE_NEW_CLIENT_FIELD = "CREATE_NEW_CLIENT_FIELD";
// открытие и закрытие карточки Клиента
export const OPEN_CLOSE_CLIENT_CARD = "OPEN_CLOSE_CLIENT_CARD";
// получение данных из полей Клиентов
export const CLIENT_INPUT_NAME_CHANGED = "CLIENT_INPUT_NAME_CHANGED";
export const CLIENT_INPUT_ORGANISATION_CHANGED = "CLIENT_INPUT_ORGANISATION_CHANGED";
export const CLIENT_INPUT_CITY_CHANGED = "USER_INPUT_CITY_CHANGED";
export const CLIENT_INPUT_PHONE_CHANGED = "CLIENT_INPUT_PHONE_CHANGED";
export const CLIENT_INPUT_EMAIL_CHANGED = "CLIENT_INPUT_EMAIL_CHANGED";
export const CLIENT_INPUT_CURRENT_TASK_DATE_CHANGED = "CLIENT_INPUT_CURRENT_TASK_DATE_CHANGED";
export const CLIENT_INPUT_CURRENT_TASK_CHANGED = "CLIENT_INPUT_CURRENT_TASK_CHANGED";
export const CLIENT_INPUT_CURRENT_CONDITION = "CLIENT_INPUT_CURRENT_CONDITION";
// валидация полей Клиентов
export const CLIENT_NAME_INVALID = "CLIENT_NAME_INVALID";
export const CLIENT_NAME_VALID = "CLIENT_NAME_VALID";
export const CLIENT_CITY_INVALID = "CLIENT_CITY_INVALID";
export const CLIENT_CITY_VALID = "CLIENT_CITY_VALID";
export const CLIENT_PHONE_INVALID = "CLIENT_PHONE_INVALID";
export const CLIENT_PHONE_VALID = "CLIENT_PHONE_VALID";
export const CLIENT_EMAIL_INVALID = "CLIENT_EMAIL_INVALID";
export const CLIENT_EMAIL_VALID = "CLIENT_EMAIL_VALID";
export const CLIENT_CURRENT_TASK_DATE_INVALID = "CLIENT_CURRENT_TASK_DATE_INVALID";
export const CLIENT_CURRENT_TASK_DATE_VALID = "CLIENT_CURRENT_TASK_DATE_VALID";
// добавление Клиента к базе
export const TRYING_TO_ADD_CLIENT = "TRYING_TO_ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";
export const ADD_CLIENT_EMPTY_FIELD_FAILED = "ADD_CLIENT_EMPTY_FIELD_FAILED";
export const CHANGE_CLIENT_DATA_EMPTY_FIELD_FAILED = "CHANGE_CLIENT_DATA_EMPTY_FIELD_FAILED";
export const ADD_CLIENT_INVALID_FIELD_FAILED = "ADD_CLIENT_INVALID_FIELD_FAILED";
// изменение данных Клиента
export const TRYING_TO_CHANGE_CLIENT_DATA = "TRYING_TO_CHANGE_CLIENT_DATA";
export const CHANGE_CLIENT_DATA_SUCCESS = "CHANGE_CLIENT_DATA_SUCCESS";
export const CHANGE_CLIENT_DATA_FAILED = "CHANGE_CLIENT_DATA_FAILED";
// удаление Клиента
export const TRYING_TO_DELETE_CLIENT = "TRYING_TO_DELETE_CLIENT";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
// получение данных из полей Клиентов
export const CLIENT_SEARCH_INPUT_CHANGED = "CLIENT_SEARCH_INPUT_CHANGED";
// результат поиска
export const GET_SEARCH_CLIENT_SUCCESS = "GET_SEARCH_CLIENT_SUCCESS";
export const CLIENT_SEARCH_INPUT_FAILED = "CLIENT_SEARCH_INPUT_FAILED";



// ДЛЯ TASK
// автоматическая загрузка задач
export const TRYING_TO_GET_TASKS = "TRYING_TO_GET_TASKS";
export const TASK_GOT_SUCCESS = "TASK_GOT_SUCCESS";
export const TASK_GOT_FAILED = "TASK_GOT_FAILED";
// создание нового поля для задач
export const CREATE_NEW_TASK_FIELD = "CREATE_NEW_TASK_FIELD";
// получение данных из полей задач
export const TASK_INPUT_CHANGED = "TASK_INPUT_CHANGED";
// сохранение задачи в базе
export const TRYING_TO_ADD_TASK = "TRYING_TO_ADD_TASK";
export const TRYING_TO_ADD_TASK_SUCCESS = "TRYING_TO_ADD_TASK_SUCCESS";
export const TASK_GOT_SUCCESS_DONE = "TASK_GOT_SUCCESS_DONE";
export const TRYING_TO_ADD_TASK_FAILED = "TRYING_TO_ADD_TASK_FAILED";
export const GOT_EMPTY_TASKS = "GOT_EMPTY_TASKS";
// изменение задачи, загруженной из базы
export const TRYING_TO_CHANGE_TASK = "TRYING_TO_CHANGE_TASK";
export const TRYING_TO_CHANGE_TASK_SUCCESS = "TRYING_TO_CHANGE_TASK_SUCCESS";
export const TRYING_TO_CHANGE_TASK_FAILED = "TRYING_TO_CHANGE_TASK_FAILED";
// удаление задачи, сохраненной в базе
export const TRYING_TO_DELETE_TASK_FROM_BASE = "TRYING_TO_DELETE_TASK";
export const DELETED_TASK_FROM_BASE_SUCCESS = "DELETED_TASK_FROM_BASE_SUCCESS";
export const DELETED_TASK_FROM_BASE_FAILED = "DELETED_TASK_FROM_BASE_FAILED";


